baseURL = ''
languageCode = 'en-us'
title = 'SubinAMathew'
theme = "ananke"

date_format = "2. January 2006"


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"


[[params.ananke_socials]]
name = "linkedin"
url = https://www.linkedin.com/in/subinamathew
[[params.ananke_socials]]
name = "twitter"
url = https://twitter.com/subinamathew
[[params.ananke_socials]]
name = "github"
url = https://github.com/subinamathew